---
- hosts: all
  sudo: true
  vars_files:
    - vars/all.yml
  roles:
    - server
    - base
    - vagrant_local
    - nginx
    - mysql
    - mongodb
    - redis
    - php
    - xdebug
    - composer
    - app
